name: Deploy to EC2

on: [push, workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull gaveenbuddhika/foodapp:latest
            sudo docker stop foodapp || true
            sudo docker rm foodapp || true
            sudo docker run -d --name foodapp -p 80:80 gaveenbuddhika/foodapp:latest