name: Deploy to EC2

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo apt-get update &&
            sudo apt-get install -y docker.io &&
            sudo systemctl start docker &&
            sudo systemctl enable docker
            sudo docker stop foodapp || true
            sudo docker rm foodapp || true
            sudo docker pull gaveenbuddhika/foodapp:latest
            sudo docker run -d --name foodapp -p 80:3000 gaveenbuddhika/foodapp:latest