name: Deploy to EC2 instance
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker stop foodapp || true
            sudo docker rm foodapp || true
            sudo docker pull gaveenbuddhika/foodapp:latest
            sudo docker run -d -p 80:80 --name foodapp gaveenbuddhika/foodapp:latest