name: Test project

on:
  # We are only going to trigger this workflow using status check of a PR
  # When a PR is opened, this workflow will be triggered and if the status check passes, the PR can be merged
  #pull_request:
   # types:
    #  - opened
      # reopened is used to trigger the workflow when a PR is reopened
      # When a new commit is pushed to the PR while it is opened the workflow will not be triggered
      # The PR has to be reopened for the workflow to be triggered
     # - reopened
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
     

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test


  fsScan:
    name: File System Vulnerability Scan
    runs-on: ubuntu-latest
  steps:
    - name: Checkout/test
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@0.20.0
      with:
        scan-type: "fs"
        ignore-unfixed: true
        format: "sarif"
        output: "trivy-fs-scan-results.sarif"
        severity: "CRITICAL"

    - name: List SARIF file
      run: ls -al trivy-fs-scan-results.sarif

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: "trivy-fs-scan-results.sarif"
